# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    echo $(whoami)
    sudo apt-get install mysql-server -y
    sudo mysql -u root -e "create database test_app_itxia;"
    sudo mysql -u root -e "set password for root@localhost = password("root");"
#  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: create mysql
#wtf
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
