# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- dev
resources:
  containers:
  - container: mysql
    image: mysql
    environment:
    - MYSQL_DATABASES=test_app_itxia
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_HOST=localhost
    - MYSQL_PORT=3306
#    - MYSQL_USER=test
#    - MYSQL_PASSWORD=test
#    - MYSQL_MY_DATABASE=my-database
    ports: "3306:3306"
    volumes:
    - "./volumes/mysql:/var/lib/mysql"

pool:
  vmImage: 'ubuntu-latest'

services:
  mysql: mysql

#wtf
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
