# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'


steps:
#配置本地数据库(用于测试)
- task: MysqlDeploymentOnMachineGroup@1
  inputs:
    TaskNameSelector: 'SqlTaskFile'
#    SqlFile: 'wtf is this'
    ServerName: 'localhost'
    DatabaseName: 'test_app_itxia'
    SqlUsername: 'root'
    SqlPassword: 'root'
#build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
